name: Lint

on:
  push:
    branches:
      - main
      - production
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 'lts/*'
          check-latest: true

      - name: npm run lint
        run: |
          npm config set fund false
          cd src
          npm ci
          npm run lint
