name: Lint

on:
  push:
    branches:
      - development
      - production
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 'lts/*'

      - run: |
          cd src
          npm ci
          npm run lint
